[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@forge-std/=/root/0x04-OnChainVoting/lib/forge-std/src/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
